spring:
  port: ${APP_PORT:8080}
  config:
    activate:
      on-profile: prod
  batch:
    jdbc:
      initialize-schema: never
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
      idle-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 500
        format_sql: true
        use_sql_comments: true
  sql:
    init:
      mode: never

logging:
  level:
    com.sprint.mission.discodeit: info
    org.hibernate.SQL: info
    org.hibernate.orm.jdbc.bind: info
    org.springframework.security: info